#ifndef DECORATORS_H
#define DECORATORS_H

#define DECOR_IGNORE_MISSING_RETURN 0x01
#define DECOR_ONETIME_ARGUMENTS 0x02
#define DECOR_OMIT_FRAME_POINTER 0x04
#define DECOR_EXTERN_FUNCTION 0x08
#define DECOR_PACKED_STRUCT 0x10

#endif